import { spawn, type StdioOptions } from "node:child_process";
import { readdirSync, writeFileSync } from "node:fs";
import { join, isAbsolute } from "node:path";
import ffmpegPath from "ffmpeg-static";

/**
 * Game-quality capture pipeline.
 *
 * The standalone renderer (render/replay) draws a tactical top-down view. To get
 * true game-quality footage you let CoD4 itself render the demo and dump frames
 * (`cl_avidemo`), then encode those frames to mp4 here. This module:
 *   - generates the in-game capture config,
 *   - launches iw3mp.exe playing the demo,
 *   - encodes the dumped frame sequence to mp4 (the part we can fully automate).
 */

/** Detect a numbered frame sequence (e.g. shot0000.tga) in a directory. */
export interface FrameSequence {
  pattern: string; // printf pattern, e.g. "shot%04d.tga"
  start: number;
  count: number;
  ext: string;
}

export function detectFrameSequence(dir: string, ext = "tga"): FrameSequence | null {
  const re = new RegExp(`^([a-zA-Z_]*?)(\\d+)\\.${ext}$`);
  let prefix: string | null = null;
  let pad = 0;
  const nums: number[] = [];
  for (const f of readdirSync(dir)) {
    const m = f.match(re);
    if (!m) continue;
    if (prefix === null) {
      prefix = m[1];
      pad = m[2].length;
    }
    if (m[1] === prefix && m[2].length === pad) nums.push(Number(m[2]));
  }
  if (prefix === null || nums.length === 0) return null;
  nums.sort((a, b) => a - b);
  // longest contiguous run from the smallest index
  let start = nums[0];
  let count = 1;
  for (let i = 1; i < nums.length; i++) {
    if (nums[i] === nums[i - 1] + 1) count++;
    else break;
  }
  return { pattern: `${prefix}%0${pad}d.${ext}`, start, count, ext };
}

export interface EncodeOptions {
  dir: string;
  out: string;
  fps: number;
  ext?: string;
  crf?: number;
}

/** Encode a numbered frame sequence in `dir` to an mp4 using bundled ffmpeg. */
export function encodeFrames(opts: EncodeOptions): Promise<{ frames: number }> {
  if (!ffmpegPath) throw new Error("ffmpeg-static binary not found.");
  const seq = detectFrameSequence(opts.dir, opts.ext ?? "tga");
  if (!seq) throw new Error(`No numbered .${opts.ext ?? "tga"} frame sequence found in ${opts.dir}`);

  const inputPattern = join(opts.dir, seq.pattern);
  const args = [
    "-y",
    "-framerate", String(opts.fps),
    "-start_number", String(seq.start),
    "-i", inputPattern,
    "-frames:v", String(seq.count),
    "-c:v", "libx264",
    "-preset", "veryfast",
    "-crf", String(opts.crf ?? 18),
    "-pix_fmt", "yuv420p",
    "-vf", "pad=ceil(iw/2)*2:ceil(ih/2)*2",
    "-movflags", "+faststart",
    opts.out,
  ];
  return new Promise((resolve, reject) => {
    const ff = spawn(ffmpegPath as unknown as string, args, { stdio: ["ignore", "ignore", "inherit"] as StdioOptions });
    ff.on("error", reject);
    ff.on("close", (code: number | null) =>
      code === 0 ? resolve({ frames: seq.count }) : reject(new Error(`ffmpeg exited with code ${code}`)),
    );
  });
}

/** In-game config that binds capture toggles and sets a fixed dump rate. */
export function buildCaptureConfig(fps: number): string {
  return [
    "// Generated by cod4-dm1-tools (capture). Exec in-game or via +exec.",
    `seta com_maxfps "${fps}"`,
    "seta cg_drawGun 1",
    'bind F9 "cl_avidemo ' + fps + '"   // start frame dump',
    'bind F10 "cl_avidemo 0"            // stop frame dump',
    "",
  ].join("\n");
}

export interface LaunchOptions {
  gameDir: string;
  exe?: string; // default iw3mp.exe
  fsGame?: string; // e.g. Mods/fps_promod_277
  demo: string; // demo name without extension
  fps: number;
  windowed?: boolean;
}

/**
 * Launch CoD4 playing a demo with the capture config loaded. Returns the child
 * process. The caller drives capture in-game (F9 start / F10 stop); frames land
 * in <fs_game>/screenshots, then `encodeFrames` turns them into mp4.
 */
export function launchPlayback(opts: LaunchOptions) {
  const exe = opts.exe ?? "iw3mp.exe";
  const exePath = isAbsolute(exe) ? exe : join(opts.gameDir, exe);
  const cfgRel = "demotools_capture.cfg";
  const cfgDir = opts.fsGame ? join(opts.gameDir, opts.fsGame) : join(opts.gameDir, "main");
  writeFileSync(join(cfgDir, cfgRel), buildCaptureConfig(opts.fps));

  const args: string[] = [];
  if (opts.fsGame) args.push("+set", "fs_game", opts.fsGame);
  if (opts.windowed) args.push("+set", "r_fullscreen", "0");
  args.push("+exec", cfgRel, "+demo", opts.demo);

  return spawn(exePath, args, { cwd: opts.gameDir, detached: true, stdio: "ignore" });
}
